Filmy_projekt/urls.py
from django.contrib import admin
from django.urls import path
from filmy_app import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('gatunki_filmy/', views.gatunki_filmy, name='gatunki_filmy'),
    path('film/<int:pk>/', views.film, name='film'),
    path('opinia_ocena/<int:film_id>/', views.opinia_ocena, name='opinia_ocena'),
    path('rejestracja/', views.rejestracja_recenzenta, name='rejestracja'),
    path('wszystkie_opinie/', views.wszystkie_opinie, name='wszystkie_opinie'),
    path('accounts/profile/', views.profile, name='profile')

]

filmy_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Gatunek(models.Model):
    """
    Model ten zawiera nazwy gatunków filmów.
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Film(models.Model):
    """
    Model z danymi dotyczącymi filmów
    """
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    director = models.CharField(max_length=200, null=True, blank=True)
    genres = models.ManyToManyField(Gatunek)

    def __str__(self):
        return self.title


class Recenzent(models.Model):
    """
    Model recenzenta - osoby wystawiającej opinię o filmie
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name} {self.surname}'


class Opinia(models.Model):
    """
    Model umożliwiający wystawinie opinii filmu
    """
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    recenzent = models.ForeignKey(Recenzent, on_delete=models.CASCADE)
    text = models.TextField(null=True)

    def __str__(self):
        return f'Recenzja od: {self.recenzent.name} {self.recenzent.surname}'


class Ocena(models.Model):
    """
    Model z ocenami dla filmów
    """
    OCENA_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    ]
    opinia = models.OneToOneField(Opinia, on_delete=models.CASCADE)
    ocena = models.IntegerField(choices=OCENA_CHOICES)

    def __str__(self):
        return f'{self.opinia.recenzent.name} {self.opinia.recenzent.surname} ocena dla {self.opinia.film.title}'

filmy_app/forms.py
from django import forms
from .models import Opinia, Ocena, Recenzent
from django.contrib.auth.models import User


class OpiniaForm(forms.ModelForm):
    """Formularz opinii."""
    class Meta:
        model = Opinia
        fields = ['text']


class OcenaForm(forms.ModelForm):
    """Formularz oceny."""
    class Meta:
        model = Ocena
        fields = ['ocena']


class RejestracjaRecenzentaForm(forms.ModelForm):
    """Formularz rejestracji"""
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirm = forms.CharField(widget=forms.PasswordInput(), label="Potwierdź hasło")

    class Meta:
        model = Recenzent
        fields = ['name', 'surname']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("password_confirm")

        if password != confirm_password:
            self.add_error('password_confirm', "Hasła nie są takie same")

    def save(self, *args, **kwargs):
        user = User.objects.create_user(self.cleaned_data['username'], password=self.cleaned_data['password'])
        recenzent = Recenzent.objects.create(user=user, name=self.cleaned_data['name'], surname=self.cleaned_data['surname'])
        return recenzent

filmy_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Film, Gatunek, Opinia, Recenzent
from django.contrib.auth.decorators import login_required
from .forms import OpiniaForm, OcenaForm, RejestracjaRecenzentaForm


# Create your views here.
def home(request):
    """
    Strona główna
    """
    return render(request, 'home.html')


def gatunki_filmy(request):
    """
    Wyświetla wszystkie gatunki i filmy
    """
    gatunki = Gatunek.objects.all()
    filmy = Film.objects.all()
    return render(request, 'gatunki_filmy.html', {'gatunki': gatunki, 'filmy': filmy})


def film(request, pk):
    """
    Wyświetla szczegółowe informacje o filmie.
    """
    film = get_object_or_404(Film, pk=pk)
    return render(request, 'film.html', {'film': film})


@login_required
def opinia_ocena(request, film_id):
    """Wystawienie opinii i oceny"""
    film = get_object_or_404(Film, pk=film_id)
    opinie = Opinia.objects.filter(film=film)

    if request.method == 'POST':
        form_opinia = OpiniaForm(request.POST)
        form_ocena = OcenaForm(request.POST)
        if form_opinia.is_valid() and form_ocena.is_valid():
            opinia = form_opinia.save(commit=False)
            opinia.film = film
            opinia.recenzent = Recenzent.objects.get(user=request.user)
            opinia.save()

            ocena = form_ocena.save(commit=False)
            ocena.opinia = opinia
            ocena.save()

            return redirect('opinia_ocena', film_id=film.id)

    else:
        form_opinia = OpiniaForm()
        form_ocena = OcenaForm()

    return render(request, 'opinia_ocena.html', {'form_opinia': form_opinia, 'form_ocena': form_ocena, 'opinie': opinie})


def rejestracja_recenzenta(request):
    """ Rejestracja recenzenta"""
    if request.method == "POST":
        form = RejestracjaRecenzentaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = RejestracjaRecenzentaForm()
    return render(request, 'rejestracja.html', {'form': form})


def wszystkie_opinie(request):
    """
    Widok wyświetlający wszystkie opinie dla wszystkich filmów.
    """
    opinie = Opinia.objects.all()

    return render(request, 'wszystkie_opinie.html', {'opinie': opinie})


@login_required
def profile(request):
    """
    Wyświetla profil recenzenta
    """
    recenzent = request.user.recenzent
    return render(request, 'profile.html', {'recenzent': recenzent})

filmy_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Films</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.min.css"></head>

</head>
<body>
    <nav>
        <li><a href="{% url 'home' %}">Strona główna</a></li>
        <li><a href="{% url 'gatunki_filmy' %}">Filmy</a></li>
        <li><a href="{% url 'wszystkie_opinie' %}">Recenzje</a></li>
        <li><a href="{% url 'rejestracja' %}">Rejestracja</a></li>
        <li><a href="{% url 'login' %}">Logowanie</a></li>
        <li><a href="{% url 'logout' %}">Wylogowanie</a></li>




    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

filmy_app/templates/film.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ film.title }}</h1>
<p>{{ film.description }}</p>
<p>Reżyser: {{ film.director }}</p>
<p>Gatunki: {% for gatunek in film.genres.all %}{{ gatunek }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
<p><a href="{% url 'opinia_ocena' film.id %}">Zobacz recenzje tego filmu bądź dokonaj recenzji</a></p>
{% endblock %}

filmy_app/templates/gatunki_filmy.html
{% extends 'base.html' %}

{% block content %}
<h1>Gatunki i Filmy</h1>

<table>
    <tr>
        <th>Gatunek</th>
        <th>Filmy</th>
    </tr>
    {% for gatunek in gatunki %}
    <tr>
        <td>{{ gatunek.name }}</td>
        <td>
            {% for film in gatunek.film_set.all %}
            <a href="{% url 'film' film.id %}">{{ film.title }}</a>
            {% empty %}
            Brak filmów w tym gatunku.
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

filmy_app/templates/home.html
{% extends 'base.html' %}
{% block content %}


   <h1>MONKOfilms</h1>
<p>Strona internetowa poświęcona wystawianiu recenzji obejrzanym przez Was filmom.</p>
<p>To właśnie tutaj możesz przejrzeć recenzje, a także dodać swoją własną recenzję na temat obejrzanego przez siebie filmu.</p>

{% endblock %}

filmy_app/templates/login.html
{% extends "base.html" %}


{% block content %}
 <form method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <button type="submit">Zaloguj się</button>
 </form>
{% endblock %}

filmy_app/templates/logout.html
{% extends "base.html" %}


{% block content %}
 <p>Ups! Nastąpiło wylogowanie z systemu. <a href="{% url 'login' %}">Zaloguj się ponownie klikając tutaj.</a></p>
{% endblock %}

filmy_app/templates/opinia_ocena.html
{% extends 'base.html' %}

{% block content %}

<h2>Opinie i oceny:</h2>

{% for opinia in opinie %}
    <h3>Recenzent: {{ opinia.recenzent.user.username }}</h3>
    <p>Opinia: {{ opinia.text }}</p>
    <p>Ocena: {{ opinia.ocena.ocena }}</p>
{% empty %}
    <p>Brak recenzji dla tego filmu.</p>
{% endfor %}

{% if user.is_authenticated %}
    <h1>Dodaj opinię i ocenę do filmu</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form_opinia.as_p }}
        {{ form_ocena.as_p }}
        <button type="submit">Dodaj opinię i ocenę</button>
    </form>
{% else %}
    <p>Aby dodać opinię, musisz się <a href="{% url 'login' %}">zalogować</a>.</p>
{% endif %}

{% endblock %}

filmy_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>Profil recenzenta</h2>
    <p>Imię: {{ recenzent.name }}</p>
    <p>Nazwisko: {{ recenzent.surname }}</p>
    <p>Użytkownik: {{ recenzent.user.username }}</p>
{% endblock %}

filmy_app/templates/rejestracja.html
{% extends 'base.html' %}

{% block content %}
    <h2>Rejestracja nowego recenzenta</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zarejestruj się</button>
    </form>
{% endblock %}

filmy_app/templates/wszystkie_opinie.html
{% extends 'base.html' %}

{% block content %}
<h2>Recenzje</h2>

{% for opinia in opinie %}
    <h3>Film: {{ opinia.film.title }}</h3>
    <h3>Recenzent: {{ opinia.recenzent.user.username }}</h3>
    <p>Opinia: {{ opinia.text }}</p>
    <p>Ocena: {{ opinia.ocena.ocena }}</p>
{% empty %}
    <p>Brak recenzji.</p>
{% endfor %}

{% endblock %}